name: Redis-Populate CI

on:
    push:

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.21"

            - name: Run tests
              run: go test ./...

    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.21"

            - name: Build
              run: go build -o populate-redis .
